name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Allow manual triggering

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: reviewdog/action-shellcheck@v1
      with:
        reporter: github-pr-review
        shellcheck_flags: '-x'
        path: '*.sh'
    
    - name: Run PowerShell Script Analyzer
      uses: reviewdog/action-psscriptanalyzer@v1
      with:
        reporter: github-pr-review
        path: '*.ps1'
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: powershell
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2 