name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Allow manual triggering

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: reviewdog/action-shellcheck@v1
      with:
        reporter: github-pr-review
        shellcheck_flags: '-x'
        path: '*.sh'
    
    - name: Run PowerShell Script Analyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force
        $results = Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -Severity Error,Warning
        if ($results) {
          Write-Host "Found $($results.Count) issues:"
          $results | Format-List
          exit 1
        } else {
          Write-Host "No issues found"
        }

    - name: Test Script Functionality
      shell: pwsh
      run: |
        ./test_script.ps1 